Remove S6 (#60)

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -8,19 +8,19 @@ on:
       - '!trunk'
 
 env:
-  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4g -Dorg.gradle.daemon=false -Dkotlin.incremental=false"
+  GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.vfs.watch=false -Dkotlin.incremental=false -Dorg.gradle.logging.stacktrace=full"
 
 jobs:
-  gradle:
+  distribution:
     runs-on: ubuntu-latest
 
     steps:
       - uses: actions/checkout@v6
-      - uses: gradle/actions/wrapper-validation@v5
       - uses: actions/setup-java@v5
         with:
           distribution: 'zulu'
           java-version-file: .github/workflows/.java-version
+      - uses: gradle/actions/setup-gradle@v5
 
       - run: ./gradlew build
 
@@ -28,11 +28,26 @@ jobs:
         with:
           name: plex-auto-trash.zip
           path: build/distributions/plex-auto-trash.zip
+          if-no-files-found: error
 
   docker:
     runs-on: ubuntu-latest
-
     steps:
       - uses: actions/checkout@v6
-      - uses: gradle/actions/wrapper-validation@v5
-      - run: docker build .
+      - run: docker build -t plex-auto-trash .
+      - run: docker run --rm plex-auto-trash --help
+
+  final-status:
+    if: ${{ !cancelled() }}
+    runs-on: ubuntu-latest
+    needs:
+      - distribution
+      - docker
+    steps:
+      - name: Check
+        run: |
+          results=$(tr -d '\n' <<< '${{ toJSON(needs.*.result) }}')
+          if ! grep -q -v -E '(failure|cancelled)' <<< "$results"; then
+            echo "One or more required jobs failed"
+            exit 1
+          fi
